#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

class ProjectEuller2
  def fib(number)
    number <= 2 ? number : fib(number - 1) + fib(number - 2)
  end

  def get_sum_of_fibonnaci_numbers_below_4000()
    sum = 0
    index = 1

    #I could use a for i < fib(i) < 4000000 but i prefer call fib to each index only once
    while true do
      fibOf = fib(index)
      break if fibOf >= 4000000

      sum = sum + fibOf if fibOf % 2 == 0
      index = index + 1
    end
    sum
  end
end
